# Generated by Django 5.2 on 2025-04-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoForceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
