# Generated by Django 5.2 on 2025-04-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoForceApp', '0002_user_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_contest_manager',
            field=models.BooleanField(default=False, help_text='Cho phép người dùng tạo và quản lý cuộc thi'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_problem_setter',
            field=models.BooleanField(default=False, help_text='Cho phép người dùng tạo và quản lý bài tập'),
        ),
    ]
