# Generated by Django 5.2 on 2025-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoForceApp', '0003_user_is_contest_manager_user_is_problem_setter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='elo',
            field=models.IntegerField(default=500),
        ),
    ]
