# Generated by Django 5.2 on 2025-04-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoForceApp', '0004_alter_user_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='problem_files/'),
        ),
    ]
