# Generated by Django 5.2 on 2025-04-20 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryptoForceApp', '0005_problem_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('cost', models.IntegerField(default=10)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='CryptoForceApp.problem')),
                ('unlocked_by', models.ManyToManyField(blank=True, related_name='unlocked_hints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
